# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import agent_pb2 as agent__pb2

GRPC_GENERATED_VERSION = '1.83.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in agent_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AgentServiceStub:
    """============================================================
    Service：平台（Python/Go/Java/TS） → Agent（sidecar）
    ============================================================
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Init = channel.unary_unary(
                '/agentapi.v1.AgentService/Init',
                request_serializer=agent__pb2.InitRequest.SerializeToString,
                response_deserializer=agent__pb2.InitResponse.FromString,
                _registered_method=True)
        self.Start = channel.unary_unary(
                '/agentapi.v1.AgentService/Start',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.Stop = channel.unary_unary(
                '/agentapi.v1.AgentService/Stop',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.ReloadConfig = channel.unary_unary(
                '/agentapi.v1.AgentService/ReloadConfig',
                request_serializer=agent__pb2.ReloadConfigRequest.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.PrepareDevice = channel.unary_unary(
                '/agentapi.v1.AgentService/PrepareDevice',
                request_serializer=agent__pb2.PrepareDeviceRequest.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.ReleaseDevice = channel.unary_unary(
                '/agentapi.v1.AgentService/ReleaseDevice',
                request_serializer=agent__pb2.ReleaseDeviceRequest.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.ResetDevice = channel.unary_unary(
                '/agentapi.v1.AgentService/ResetDevice',
                request_serializer=agent__pb2.ResetDeviceRequest.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/agentapi.v1.AgentService/ListDevices',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.ForceCloseSession = channel.unary_unary(
                '/agentapi.v1.AgentService/ForceCloseSession',
                request_serializer=agent__pb2.ForceCloseSessionRequest.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.SetQuality = channel.unary_unary(
                '/agentapi.v1.AgentService/SetQuality',
                request_serializer=agent__pb2.SetQualityRequest.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.SendControl = channel.unary_unary(
                '/agentapi.v1.AgentService/SendControl',
                request_serializer=agent__pb2.SendControlRequest.SerializeToString,
                response_deserializer=agent__pb2.CommonResponse.FromString,
                _registered_method=True)
        self.Health = channel.unary_unary(
                '/agentapi.v1.AgentService/Health',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.HealthResponse.FromString,
                _registered_method=True)
        self.StreamEvents = channel.unary_stream(
                '/agentapi.v1.AgentService/StreamEvents',
                request_serializer=agent__pb2.Empty.SerializeToString,
                response_deserializer=agent__pb2.AgentEvent.FromString,
                _registered_method=True)


class AgentServiceServicer:
    """============================================================
    Service：平台（Python/Go/Java/TS） → Agent（sidecar）
    ============================================================
    """

    def Init(self, request, context):
        """初始化：注入全局配置（仅 UNINITIALIZED 状态合法，重复调用 → ERR_ALREADY_INIT）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Start(self, request, context):
        """启动：Agent 就绪（等待 PrepareDevice / 信令连接）。幂等。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Stop(self, request, context):
        """优雅停止：回收所有设备与会话，释放资源（进程不退出）。幂等，状态回 UNINITIALIZED。
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReloadConfig(self, request, context):
        """全局配置热更新（全量替换；不中断现有会话，新准备设备生效）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareDevice(self, request, context):
        """设备管理：用户连接准备阶段注入设备配置（已存在 = 平滑更新）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReleaseDevice(self, request, context):
        """设备管理：平台回收设备，断开其信令连接并从设备列表移除
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetDevice(self, request, context):
        """强制清除设备内存配置（先断开，原子清除；设备保留在 ListDevices，configured=false）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """查询本机所有设备状态（busy / idle / configured / signaling_connected）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForceCloseSession(self, request, context):
        """会话干预（绝对管理权）：强制关闭会话，浏览器收到 preempted
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetQuality(self, request, context):
        """画质档位强制设定（无会话时仅持久化，后续会话继承）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendControl(self, request, context):
        """平台代发控制指令（fire-and-forget）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Health(self, request, context):
        """探活
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Agent → 平台：事件流（长连接，fan-out 广播，断线不重放）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AgentServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Init': grpc.unary_unary_rpc_method_handler(
                    servicer.Init,
                    request_deserializer=agent__pb2.InitRequest.FromString,
                    response_serializer=agent__pb2.InitResponse.SerializeToString,
            ),
            'Start': grpc.unary_unary_rpc_method_handler(
                    servicer.Start,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'Stop': grpc.unary_unary_rpc_method_handler(
                    servicer.Stop,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'ReloadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadConfig,
                    request_deserializer=agent__pb2.ReloadConfigRequest.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'PrepareDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareDevice,
                    request_deserializer=agent__pb2.PrepareDeviceRequest.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'ReleaseDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ReleaseDevice,
                    request_deserializer=agent__pb2.ReleaseDeviceRequest.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'ResetDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetDevice,
                    request_deserializer=agent__pb2.ResetDeviceRequest.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.ListDevicesResponse.SerializeToString,
            ),
            'ForceCloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.ForceCloseSession,
                    request_deserializer=agent__pb2.ForceCloseSessionRequest.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'SetQuality': grpc.unary_unary_rpc_method_handler(
                    servicer.SetQuality,
                    request_deserializer=agent__pb2.SetQualityRequest.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'SendControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SendControl,
                    request_deserializer=agent__pb2.SendControlRequest.FromString,
                    response_serializer=agent__pb2.CommonResponse.SerializeToString,
            ),
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.HealthResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=agent__pb2.Empty.FromString,
                    response_serializer=agent__pb2.AgentEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'agentapi.v1.AgentService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('agentapi.v1.AgentService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AgentService:
    """============================================================
    Service：平台（Python/Go/Java/TS） → Agent（sidecar）
    ============================================================
    """

    @staticmethod
    def Init(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/Init',
            agent__pb2.InitRequest.SerializeToString,
            agent__pb2.InitResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/Start',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Stop(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/Stop',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReloadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/ReloadConfig',
            agent__pb2.ReloadConfigRequest.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/PrepareDevice',
            agent__pb2.PrepareDeviceRequest.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReleaseDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/ReleaseDevice',
            agent__pb2.ReleaseDeviceRequest.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResetDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/ResetDevice',
            agent__pb2.ResetDeviceRequest.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/ListDevices',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForceCloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/ForceCloseSession',
            agent__pb2.ForceCloseSessionRequest.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetQuality(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/SetQuality',
            agent__pb2.SetQualityRequest.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SendControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/SendControl',
            agent__pb2.SendControlRequest.SerializeToString,
            agent__pb2.CommonResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/agentapi.v1.AgentService/Health',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/agentapi.v1.AgentService/StreamEvents',
            agent__pb2.Empty.SerializeToString,
            agent__pb2.AgentEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
