// Package common defines shared WebSocket message types used by signaling
// server, browser frontend, and agent.
package common

// WsMsg is the envelope for all WebSocket signaling messages.
type WsMsg struct {
	Type      string        `json:"type"`
	Offer     *SessionDesc  `json:"offer,omitempty"`
	Answer    *SessionDesc  `json:"answer,omitempty"`
	Candidate *IceCandidate `json:"candidate,omitempty"`
	PCID      string        `json:"pc_id,omitempty"` // error / registration id
	Message   string        `json:"message,omitempty"`
	Data      map[string]any `json:"data,omitempty"`

	// Agent registration fields
	ServiceID    string `json:"service_id,omitempty"`
	InstanceID   string `json:"instance_id,omitempty"`
	DeviceSerial string `json:"device_serial,omitempty"`

	// ICE servers distributed by signaling server
	IceServers []IceServerEntry `json:"ice_servers,omitempty"`
	TTL        int              `json:"ttl,omitempty"`

	// SessionID is generated by signaling for each browser WebSocket
	// connection. It allows the Agent to route messages to the correct
	// SessionCtx goroutine and enables clean preemption.
	SessionID string `json:"session_id,omitempty"`

	// Relay fields: used by /ws/relay/ endpoint for generic
	// message forwarding between browser and agent without
	// triggering the bound/unbound lifecycle.
	RelayID  string         `json:"relay_id,omitempty"`  // correlation ID
	Payload  map[string]any `json:"payload,omitempty"`   // nested inner message
}

// IceServerEntry represents a single ICE (STUN/TURN) server entry for the browser.
type IceServerEntry struct {
	URLs           []string `json:"urls"`
	Username       string   `json:"username,omitempty"`
	Credential     string   `json:"credential,omitempty"`
	CredentialType string   `json:"credentialType,omitempty"` // "password" or "oauth"
}

// SessionDesc is an SDP session description (offer or answer).
type SessionDesc struct {
	SDP  string `json:"sdp"`
	Type string `json:"type"`
}

// IceCandidate carries a single ICE candidate.
type IceCandidate struct {
	Candidate     string  `json:"candidate"`
	SDPMid        *string `json:"sdpMid"`
	SDPMLineIndex *uint16 `json:"sdpMLineIndex"`
}

// Message type constants.
const (
	TypeOffer         = "offer"
	TypeAnswer        = "answer"
	TypeIceCandidate  = "ice_candidate"
	TypeError         = "error"
	TypePing          = "ping"
	TypePong          = "pong"
	TypeFirstFrame    = "first_frame"
	TypeDecoderStats  = "decoder_stats"
	TypeDecoderStatus = "decoder_status"
	TypeResetVideo    = "reset_video"
	// TypeStreamDead tells the browser the scrcpy stream died mid-session
	// (server process exited). Frontend should treat it as a connection
	// loss and auto-reconnect; the warm pool will cold-start a fresh server.
	TypeStreamDead    = "stream_dead"

	// Browser ↔ Agent: connection preemption
	TypeQueryStatus = "query_status" // Browser → Agent: is device busy?
	TypeStatusResp  = "status_resp"  // Agent → Browser: {busy: bool}
	TypePreempted   = "preempted"   // Agent → Browser: device was preempted by another user

	// Agent <-> signaling
	TypeRegister    = "register"
	TypeIceServers  = "ice_servers" // Signaling → Browser/Agent: ICE server list
	TypeBound       = "bound"
	TypeUnbound     = "unbound"
	TypeAgentStatus = "agent_status"
)
