package agent

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"scrcpy-webrtc-remote/agent/internal/adb"
	"scrcpy-webrtc-remote/agent/internal/gateway"
	"scrcpy-webrtc-remote/agent/internal/portpool"
	bridgewebrtc "scrcpy-webrtc-remote/agent/internal/webrtc"
	"scrcpy-webrtc-remote/pkg/common"
	"scrcpy-webrtc-remote/pkg/config"
	"scrcpy-webrtc-remote/pkg/debughooks"
	"scrcpy-webrtc-remote/pkg/logger"
)

// Device state constants for the controller's state machine.
const (
	deviceIdle int32 = 0 // No active WebRTC connection
	deviceBusy int32 = 1 // WebRTC connection is active
)

const (
	eventQueueSize = 32  // Buffer size for per-session event channels
	maxSessions    = 5   // Maximum concurrent session contexts
	preemptTimeout = 10 * time.Second
)

const (
	heartbeatIntervalSec = 30   // WebSocket 心跳间隔（秒）
	retryFastAttempts    = 12   // 快速重连次数（间隔 5s）
	retryFastInterval    = 5 * time.Second
	retrySlowInterval    = 5 * time.Minute // 之后的慢速重连间隔
)

// SessionCtx holds all state for one browser connection.
// Each browser WebSocket gets its own SessionCtx with an
// independent goroutine processing events sequentially.
type SessionCtx struct {
	id         string
	stopChan   chan struct{}       // Closed to signal preemption / stop
	eventQueue chan common.WsMsg   // Ordered event channel from main loop
	done       chan struct{}       // Closed when cleanup completes

	peer    *bridgewebrtc.PeerManager
	mgr     *gateway.Manager
	ctrl    *Controller // back-reference for quality tier persistence

	// session is assigned asynchronously by prepareSession (offer handling
	// no longer blocks on scrcpy startup). Guard with mu; sessionReady is
	// closed once the session is Streaming and media can flow.
	mu           sync.Mutex
	session      *gateway.Session
	sessionReady chan struct{}
	// prepareOnce guards prepareSession against duplicate offers: a browser
	// reconnect may deliver two offers to the same SessionCtx, and two
	// concurrent prepareSession goroutines would both close(sessionReady)
	// → "close of closed channel" panic (observed 2026-08-14).
	prepareOnce sync.Once

	// pendingCandidates buffers trickled ICE candidates that arrive before
	// the peer is created (the peer waits for the scrcpy session, which can
	// take several seconds). Dropping them would lose the browser's early
	// host/srflx candidates and prevent NAT pinholing on the direct path.
	pendingCandidates []*common.IceCandidate

	ws   *Client
	inst config.InstanceConfig

	// ICE servers snapshot taken at session creation time
	signalingSTUN []string
	signalingTURN *config.TurnServerConfig

	// Shared device state pointer (set by Controller)
	deviceState *atomic.Int32

	// Per-session bitrate hysteresis
	initialBitrate    int
	lastBitrate       int
	lastBitrateChange time.Time
	lastLossLowTime   time.Time // start of sustained low-loss period for recovery

	// Bitrate floor (configurable, default 400 kbps). Prevents loss-based BWE
	// from driving the encoder into a zombie stream (30 kbps is unusable for
	// cloud gaming;宁可断开也不要僵尸流).
	minBitrate int

	// Track the magnitude of the last bitrate drop to detect overly
	// aggressive BWE reactions.
	lastBitrateDropPct float64

	// preemptedByForce 标记本会话是被 ForceCloseSession / relay preempt
	// 强制结束的（而非浏览器主动 unbound）。用于抑制随后 signaling 的
	// unbound 消息重复上报 user_unbound 事件（竞态见 preemptAndWait）。
	preemptedByForce atomic.Bool

	// debug is the optional debug extension hook (nil in open-source
	// builds; a closed-source Hooks implementation is injected by the
	// platform binary). All debug protocol handling, metric sampling and
	// weak-network simulation live behind this nil-checked interface.
	debug debughooks.Hooks
}

// Controller is the agent-side orchestrator for one device instance.
// It routes messages from signaling to the correct SessionCtx goroutine
// and manages the lifecycle of all sessions (create, preempt, cleanup).
// 平台化后每个设备一个 Controller，由 DeviceManager 管理；配置经 ConfigStore
// 惰性读取（ReloadConfig 对新会话生效，不中断现有会话）。
type Controller struct {
	store *ConfigStore
	inst  config.InstanceConfig
	ws    *Client
	wsMu  sync.Mutex // guards ws (written by runOnce, closed by Stop)
	pool  *portpool.Pool
	adbCli *adb.Client

	manager *gateway.Manager

	// connectParams 覆盖信令连接参数（PrepareDevice.connect_params）。
	connectParams ConnectParams

	// Session management — map keyed by session_id (generated by signaling)
	sessions         map[string]*SessionCtx
	currentSessionID string
	mu               sync.Mutex

	// ICE servers received from signaling (shared, applied to new sessions)
	signalingSTUN []string
	signalingTURN *config.TurnServerConfig

	// Device state machine: Idle (no active connection) or Busy (WebRTC connected)
	deviceState atomic.Int32

	// signalingConnected tracks the signaling WS liveness, observable via
	// ListDevices.signaling_connected.
	signalingConnected atomic.Bool
	// registeredAt is set on each successful connect (for connected_seconds).
	registeredAt atomic.Int64 // unix seconds

	// stopChan closes to make Run's reconnect loop exit (Release/Reset/Stop).
	stopChan chan struct{}

	// qualityBitrate is the user-selected quality tier (bps), persisted at
	// controller level so reconnects and new sessions inherit it.
	// 0 means "not explicitly selected" → use scrcpy.video_bit_rate (原画).
	qualityBitrate atomic.Int64

	// hooks 是平台事件上报扩展点（nil 即禁用，见 hooks.go）。
	hooks PlatformHooks

	// debug is the optional debug extension hook propagated to every
	// SessionCtx. nil in open-source builds.
	debug debughooks.Hooks
}

// SetDebugHooks injects the optional debug extension (closed-source).
// Passing nil disables all debug functionality. Must be called before Run.
func (c *Controller) SetDebugHooks(h debughooks.Hooks) {
	c.debug = h
}

// NewSharedPortPool creates a port pool that should be shared across all
// controller instances to prevent ADB forward port conflicts on the host.
func NewSharedPortPool(start, size int) *portpool.Pool {
	return portpool.New(start, size)
}

// AutoConnectDevices checks each configured device against `adb devices`
// and runs `adb connect` for any TCP/IP device not yet connected.
func AutoConnectDevices(agentCfg config.AgentConfig, instances []config.InstanceConfig) {
	adbCli := adb.New(agentCfg.ADBPath)
	connected, err := adbCli.Devices()
	if err != nil {
		logger.Warn("adb devices failed, skipping auto-connect", "err", err)
		return
	}
	connectedSet := make(map[string]bool, len(connected))
	for _, s := range connected {
		connectedSet[s] = true
	}
	for _, inst := range instances {
		if connectedSet[inst.DeviceSerial] {
			continue
		}
		if !strings.Contains(inst.DeviceSerial, ":") {
			// USB devices (no port) expected to be connected by cable
			continue
		}
		logger.Info("adb connecting device", "serial", inst.DeviceSerial)
		if err := adbCli.Connect(inst.DeviceSerial); err != nil {
			logger.Warn("adb connect failed, device may be unavailable",
				"serial", inst.DeviceSerial, "err", err)
		} else {
			logger.Info("adb connect succeeded", "serial", inst.DeviceSerial)
		}
	}
}

// newController creates a controller backed by a ConfigStore (sidecar path).
// 修复历史 bug：adb 可执行路径取配置的 adb_path，而非硬编码 "adb"。
func newController(store *ConfigStore, inst config.InstanceConfig, pool *portpool.Pool, hooks PlatformHooks, cp ConnectParams) *Controller {
	cfg := store.ForDevice(inst.DeviceSerial)
	adbCli := adb.New(cfg.ADBPath)
	manager := gateway.NewManager(adbCli, pool, cfg.Scrcpy)

	return &Controller{
		store:         store,
		inst:          inst,
		pool:          pool,
		adbCli:        adbCli,
		manager:       manager,
		connectParams: cp,
		sessions:      make(map[string]*SessionCtx),
		stopChan:      make(chan struct{}),
		hooks:         hooks,
	}
}

// Config returns the current effective config (global + this device's
// per-device overrides), re-read on each call so ReloadConfig takes effect
// for new sessions without interrupting active ones.
func (c *Controller) Config() config.AgentConfig {
	if cfg := c.store.ForDevice(c.inst.DeviceSerial); cfg != nil {
		return *cfg
	}
	return config.AgentConfig{}
}

// SignalingConnected reports whether the signaling WS is currently alive.
func (c *Controller) SignalingConnected() bool {
	return c.signalingConnected.Load()
}

// SetPlatformHooks injects the platform event hooks (nil disables).
func (c *Controller) SetPlatformHooks(h PlatformHooks) {
	c.hooks = h
}

// SetConnectParams overrides the signaling connection params.
func (c *Controller) SetConnectParams(cp ConnectParams) {
	c.connectParams = cp
}

// reportDeviceStatus pushes a DeviceStatusChanged event for this device
// (busy state, used both on connect and on explicit status changes).
func (c *Controller) reportDeviceStatus() {
	if c.hooks == nil {
		return
	}
	c.hooks.OnDeviceStatus(c.inst.DeviceSerial, c.inst.InstanceID, c.deviceState.Load() == deviceBusy)
}

// setSignalingDown resets signaling state and reports the disconnection
// (AgentError code ERR_SIGNALING_DISCONNECTED). 所有管理 RPC 均为本地操作、
// 不依赖信令在线，因此该码只经 AgentError 事件上报（见 PLATFORM-API.md §7）。
// 首次连接失败（如不可达 signaling_url 配置）同样上报，供测试与平台观测。
func (c *Controller) setSignalingDown(err error) {
	c.signalingConnected.Store(false)
	c.registeredAt.Store(0)
	if c.hooks != nil {
		c.hooks.OnError(c.inst.DeviceSerial, c.inst.InstanceID,
			"ERR_SIGNALING_DISCONNECTED", err.Error())
		c.hooks.OnDeviceStatus(c.inst.DeviceSerial, c.inst.InstanceID,
			c.deviceState.Load() == deviceBusy)
	}
}

// Stop tears the controller down: closes the signaling WS (unblocks runOnce),
// closes the reconnect loop, and stops all sessions. Idempotent.
func (c *Controller) Stop() {
	select {
	case <-c.stopChan:
		// already stopped
	default:
		close(c.stopChan)
	}
	c.wsMu.Lock()
	if c.ws != nil {
		_ = c.ws.Close()
	}
	c.wsMu.Unlock()
	c.shutdownAll()
	c.signalingConnected.Store(false)
}

// CurrentSession returns the active SessionCtx (nil when idle).
func (c *Controller) CurrentSession() *SessionCtx {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.sessions[c.currentSessionID]
}

// CurrentSessionID returns the active session id ("" when idle).
func (c *Controller) CurrentSessionID() string {
	c.mu.Lock()
	defer c.mu.Unlock()
	return c.currentSessionID
}

// Busy reports whether a WebRTC session is active.
func (c *Controller) Busy() bool {
	return c.deviceState.Load() == deviceBusy
}

// ConnectedSeconds returns the elapsed time of the current signaling
// connection (0 when disconnected).
func (c *Controller) ConnectedSeconds() int32 {
	start := c.registeredAt.Load()
	if start == 0 {
		return 0
	}
	sec := time.Now().Unix() - start
	if sec < 0 {
		return 0
	}
	return int32(sec)
}

// ForceCloseSession forcibly closes the session (absolute management right):
// the old browser gets a preempted message and the SessionCtx is stopped.
// reason 透传到 SessionStopped 事件的 reason 字段（空则默认 "forced"）。
// Returns an error when the session_id is unknown (ERR_SESSION_NOT_FOUND).
func (c *Controller) ForceCloseSession(sessionID, reason string) error {
	c.mu.Lock()
	ctx := c.sessions[sessionID]
	c.mu.Unlock()
	if ctx == nil {
		return fmt.Errorf("session not found")
	}
	if reason == "" {
		reason = "forced"
	}
	logger.Info("force close session (platform)",
		"session_id", sessionID, "serial", c.inst.DeviceSerial, "reason", reason)
	c.preemptAndWait(ctx, sessionID, reason)
	return nil
}

// SetQuality persists the quality tier and applies it to an active session
// (through the session event queue to stay race-free with the bitrate ladder).
// 无会话时仅持久化，后续会话继承该档位（见 PLATFORM-API.md §3.8）。
func (c *Controller) SetQuality(level string) error {
	switch level {
	case "clear", "hd", "original":
	default:
		return fmt.Errorf("invalid quality level: %q", level)
	}
	bitrate := c.tierBitrate(c.Config(), level)
	c.qualityBitrate.Store(int64(bitrate))

	if ctx := c.CurrentSession(); ctx != nil {
		select {
		case ctx.eventQueue <- common.WsMsg{Type: "set_quality", Data: map[string]any{"level": level}}:
		default:
			logger.Warn("set_quality dropped: event queue full", "session_id", ctx.id)
		}
	}
	return nil
}

// SendControlRaw forwards a platform-issued control message to the active
// session's scrcpy (fire-and-forget, 见 PLATFORM-API.md §3.9)。无活动会话时
// 静默成功，不做缓存。
func (c *Controller) SendControlRaw(ctrlType string, data map[string]any) error {
	if ctrlType == "" {
		return fmt.Errorf("missing control type")
	}
	ctx := c.CurrentSession()
	if ctx == nil {
		return nil
	}
	ctx.dispatchControl(ctrlType, data)
	return nil
}

// Run is the top-level event loop for this device instance. It connects to
// the signaling server and retries indefinitely when the WebSocket drops:
//
//	attempts 1–12: every 5 seconds
//	attempts 13+:  every 5 minutes
//
// Close the controller via Stop() to exit the retry loop.
func (c *Controller) Run() {
	attempts := 0
	for {
		if err := c.runOnce(); err != nil {
			logger.Warn("signaling connection lost, retrying",
				"instance", c.inst.InstanceID,
				"attempt", attempts+1,
				"err", err)
		}
		attempts++
		select {
		case <-c.stopChan:
			logger.Info("controller stopped", "instance", c.inst.InstanceID,
				"serial", c.inst.DeviceSerial)
			return
		case <-time.After(backoffDelay(attempts)):
		}
	}
}

// backoffDelay returns the sleep duration before the next reconnect attempt.
// First retryFastAttempts attempts: retryFastInterval. Beyond that: retrySlowInterval.
func backoffDelay(attempt int) time.Duration {
	if attempt <= retryFastAttempts {
		return retryFastInterval
	}
	return retrySlowInterval
}

// runOnce connects to signaling, starts the heartbeat, and enters the
// main message loop. Returns on any unrecoverable error (e.g. WS read failure).
func (c *Controller) runOnce() error {
	cfg := c.Config()
	ws, err := ConnectWithParams(cfg.SignalingURL, cfg.ServiceID,
		c.inst.InstanceID, c.inst.DeviceSerial, c.connectParams)
	if err != nil {
		// 信令连接失败：上报 AgentError + 状态复位（可经不可达 signaling_url 配置触发）。
		c.setSignalingDown(err)
		return fmt.Errorf("connect to signaling: %w", err)
	}
	c.wsMu.Lock()
	c.ws = ws
	c.wsMu.Unlock()
	defer ws.Close()

	c.signalingConnected.Store(true)
	c.registeredAt.Store(time.Now().Unix())
	c.reportDeviceStatus()

	// Background heartbeat to keep the WebSocket alive through proxies.
	ctx, cancel := context.WithCancel(context.Background())
	defer cancel()
	ws.Heartbeat(ctx, time.Duration(heartbeatIntervalSec)*time.Second)

	logger.Info("agent instance connected",
		"service", cfg.ServiceID,
		"instance", c.inst.InstanceID,
		"serial", c.inst.DeviceSerial)

	// Stop() closes the WS to unblock the blocking Read below; on any return
	// from runOnce (ws drop, Stop, connect failure) reset signaling state.
	defer c.setSignalingDown(fmt.Errorf("signaling connection closed"))

	// Main message loop — routes messages to SessionCtx goroutines
	for {
		msg, err := ws.Read()
		if err != nil {
			c.shutdownAll()
			return fmt.Errorf("ws read: %w", err)
		}

		switch msg.Type {
		case common.TypeBound:
			logger.Info("browser bound", "instance", c.inst.InstanceID,
				"session_id", msg.SessionID)
			if err := c.handleBound(msg); err != nil {
				logger.Error("handle bound failed", "err", err)
				c.shutdownAll()
				return err
			}

		case common.TypeUnbound:
			logger.Info("browser unbound", "instance", c.inst.InstanceID,
				"session_id", msg.SessionID)
			c.handleUnbound(msg)

		case common.TypeIceServers:
			// Shared across sessions — store in Controller
			c.signalingSTUN = nil
			c.signalingTURN = nil
			for _, e := range msg.IceServers {
				urls := make([]string, len(e.URLs))
				copy(urls, e.URLs)
				if e.Username == "" && e.Credential == "" {
					c.signalingSTUN = append(c.signalingSTUN, urls...)
				} else {
					if c.signalingTURN == nil {
						c.signalingTURN = &config.TurnServerConfig{
							URLs: urls, Username: e.Username, Credential: e.Credential,
						}
					}
				}
			}
			logger.Info("received ICE servers from signaling",
				"stun", len(c.signalingSTUN), "turn", c.signalingTURN != nil,
				"ttl", msg.TTL)

		case "relay":
			// Generic relay message from browser via signaling.
			if msg.Payload == nil || msg.RelayID == "" {
				continue
			}
			innerType, _ := msg.Payload["type"].(string)
			switch innerType {
			case "query_status":
				busy := c.deviceState.Load() == deviceBusy
				c.ws.Send(common.WsMsg{
					Type:    "relay",
					RelayID: msg.RelayID,
					Payload: map[string]any{
						"type": "status_resp",
						"busy": busy,
					},
				})
			case "preempt":
				c.handleRelayPreempt(msg)
			}

		case common.TypePong:
			// heartbeat reply from signaling — silently ignore
			continue

		default:
			// Route to SessionCtx by session_id
			if msg.SessionID == "" {
				logger.Warn("message without session_id, dropping",
					"type", msg.Type)
				continue
			}
			c.routeToSession(msg)
		}
	}
}

// ---------------------------------------------------------------------------
// Session lifecycle: Bound / Unbound
// ---------------------------------------------------------------------------

// handleBound creates a new SessionCtx and starts its goroutine.
// If another session is active, it preempts the old one first.
func (c *Controller) handleBound(msg common.WsMsg) error {
	sessionID := msg.SessionID
	if sessionID == "" {
		return fmt.Errorf("bound without session_id")
	}

	// Check session limit
	c.mu.Lock()
	if len(c.sessions) >= maxSessions {
		c.mu.Unlock()
		logger.Warn("too many sessions, rejecting bound", "session_id", sessionID)
		return fmt.Errorf("max sessions (%d) reached", maxSessions)
	}

	// If a different session is active, preempt it
	oldID := c.currentSessionID
	oldCtx := c.sessions[oldID]
	c.mu.Unlock()

	if oldID != "" && oldID != sessionID && oldCtx != nil {
		logger.Warn("preempting existing session for new connection",
			"old_session", oldID, "new_session", sessionID)
		c.preemptAndWait(oldCtx, oldID, "forced")
	}

	// Create new SessionCtx
	ctx := c.newSessionCtx(sessionID)

	c.mu.Lock()
	c.sessions[sessionID] = ctx
	c.currentSessionID = sessionID
	c.mu.Unlock()

	go ctx.run()
	logger.Info("session context created", "session_id", sessionID)

	if c.hooks != nil {
		c.hooks.OnSessionStarted(c.inst.DeviceSerial, c.inst.InstanceID, sessionID)
	}
	return nil
}

// handleUnbound signals the target SessionCtx to stop and waits for cleanup.
func (c *Controller) handleUnbound(msg common.WsMsg) {
	sessionID := msg.SessionID
	if sessionID == "" {
		logger.Warn("unbound without session_id")
		return
	}

	c.mu.Lock()
	ctx := c.sessions[sessionID]
	c.mu.Unlock()

	if ctx == nil {
		logger.Warn("unbound for unknown session", "session_id", sessionID)
		return
	}

	logger.Info("stopping session", "session_id", sessionID)

	// Signal stop (idempotent via select)
	select {
	case <-ctx.stopChan:
		// already stopped
	default:
		close(ctx.stopChan)
	}

	// Wait for cleanup
	<-ctx.done

	c.mu.Lock()
	delete(c.sessions, sessionID)
	if c.currentSessionID == sessionID {
		c.currentSessionID = ""
	}
	c.mu.Unlock()

	c.deviceState.Store(deviceIdle)
	c.reportDeviceStatus()

	// 若会话已被 ForceCloseSession/preempt 强制结束，signaling 随后的
	// unbound 只做清理，不再重复上报 user_unbound（forced 事件已由
	// preemptAndWait 发出）。
	if c.hooks != nil && !ctx.preemptedByForce.Load() {
		c.hooks.OnSessionStopped(c.inst.DeviceSerial, c.inst.InstanceID,
			sessionID, "user_unbound")
	}

	logger.Info("session fully removed", "session_id", sessionID)
}

// ---------------------------------------------------------------------------
// Relay: query_status / preempt
// ---------------------------------------------------------------------------

// handleRelayPreempt handles a relay preempt request from a new browser
// before it opens the /ws/browser/ connection.
func (c *Controller) handleRelayPreempt(msg common.WsMsg) {
	c.mu.Lock()
	oldID := c.currentSessionID
	oldCtx := c.sessions[oldID]
	c.mu.Unlock()

	if oldCtx != nil {
		logger.Warn("relay preempt: stopping old session",
			"old_session", oldID)
		c.preemptAndWait(oldCtx, oldID, "forced")
	} else {
		logger.Info("relay preempt: no active session to preempt")
	}

	c.ws.Send(common.WsMsg{
		Type:    "relay",
		RelayID: msg.RelayID,
		Payload: map[string]any{
			"type": "preempt_resp",
			"ok":   true,
		},
	})
}

// preemptAndWait sends TypePreempted to the old browser, signals the old
// SessionCtx to stop via stopChan, and waits for cleanup with a timeout.
// reason 透传到 SessionStopped 事件（relay/bound preempt 传 "forced"）。
func (c *Controller) preemptAndWait(ctx *SessionCtx, sessionID, reason string) {
	// Mark as force-preempted: a subsequent signaling unbound (triggered by
	// the browser WS being closed) must NOT also emit user_unbound.
	ctx.preemptedByForce.Store(true)

	// Notify old browser — signaling will forward this to the old browser WS
	c.ws.Send(common.WsMsg{Type: common.TypePreempted, SessionID: sessionID})

	// Signal stop
	select {
	case <-ctx.stopChan:
		// already stopped
	default:
		close(ctx.stopChan)
	}

	// Wait for cleanup with timeout
	select {
	case <-ctx.done:
		logger.Info("old session cleaned up", "session_id", sessionID)
	case <-time.After(preemptTimeout):
		logger.Warn("old session cleanup timeout, forcing removal",
			"session_id", sessionID)
	}

	// Remove from map
	c.mu.Lock()
	delete(c.sessions, sessionID)
	if c.currentSessionID == sessionID {
		c.currentSessionID = ""
	}
	c.mu.Unlock()

	c.deviceState.Store(deviceIdle)
	c.reportDeviceStatus()

	if c.hooks != nil {
		c.hooks.OnSessionStopped(c.inst.DeviceSerial, c.inst.InstanceID,
			sessionID, reason)
	}
}

// ---------------------------------------------------------------------------
// Message routing
// ---------------------------------------------------------------------------

// routeToSession delivers a message to the appropriate SessionCtx event queue.
// Non-blocking on the send side: if the queue is full, the message is dropped.
func (c *Controller) routeToSession(msg common.WsMsg) {
	c.mu.Lock()
	ctx := c.sessions[msg.SessionID]
	c.mu.Unlock()

	if ctx == nil {
		logger.Warn("message for unknown session, dropping",
			"type", msg.Type, "session_id", msg.SessionID)
		return
	}

	select {
	case ctx.eventQueue <- msg:
	default:
		logger.Warn("session event queue full, dropping message",
			"type", msg.Type, "session_id", msg.SessionID)
	}
}

// ---------------------------------------------------------------------------
// SessionCtx factory
// ---------------------------------------------------------------------------

func (c *Controller) newSessionCtx(id string) *SessionCtx {
	cfg := c.Config()
	minBitrate := cfg.Scrcpy.MinVideoBitRate
	if minBitrate <= 0 {
		minBitrate = 400_000
	}
	bitrate := c.currentQualityBitrate(cfg)
	return &SessionCtx{
		id:           id,
		stopChan:     make(chan struct{}),
		eventQueue:   make(chan common.WsMsg, eventQueueSize),
		done:         make(chan struct{}),
		mgr:          c.manager,
		ctrl:         c,
		ws:           c.ws,
		inst:         c.inst,
		deviceState:  &c.deviceState,
		// Snapshot shared ICE servers at creation time
		signalingSTUN: append([]string(nil), c.signalingSTUN...),
		signalingTURN: c.signalingTURN,
		minBitrate:    minBitrate,
		// Inherit the user-selected quality tier (0 → 原画 = video_bit_rate).
		initialBitrate: bitrate,
		lastBitrate:    bitrate,
		debug:          c.debug,
	}
}

// ---------------------------------------------------------------------------
// Quality tiers (清晰度档位) — fixed resolution, bitrate-only switching
// ---------------------------------------------------------------------------

// tierBitrate maps a quality level ("clear" 清晰 / "hd" 高清 / other → 原画)
// to its encoder bitrate from config.
func (c *Controller) tierBitrate(cfg config.AgentConfig, level string) int {
	scfg := cfg.Scrcpy
	switch level {
	case "clear":
		if scfg.ClearBitrate > 0 {
			return scfg.ClearBitrate
		}
		return 2_000_000
	case "hd":
		if scfg.HDBitrate > 0 {
			return scfg.HDBitrate
		}
		return 6_000_000
	default: // "original" 原画
		return scfg.VideoBitRate
	}
}

// currentQualityBitrate returns the selected tier bitrate (原画 when the
// user has not explicitly chosen a tier).
func (c *Controller) currentQualityBitrate(cfg config.AgentConfig) int {
	if b := c.qualityBitrate.Load(); b > 0 {
		return int(b)
	}
	return cfg.Scrcpy.VideoBitRate
}

// applyQuality switches the encoder to the selected tier. Runs on the
// SessionCtx goroutine (via eventQueue) so bitrate fields stay race-free.
// The selection is persisted on the Controller so reconnects inherit it.
func (ctx *SessionCtx) applyQuality(level string) {
	bitrate := ctx.ctrl.tierBitrate(ctx.ctrl.Config(), level)
	ctx.ctrl.qualityBitrate.Store(int64(bitrate))

	ctx.initialBitrate = bitrate
	ctx.lastBitrate = bitrate
	ctx.lastBitrateChange = time.Now() // hold the auto ladder briefly

	ctx.sendCtrl(gateway.BuildChangeBitrate(bitrate))
	if ctx.peer != nil {
		ctx.peer.SetCurrentBitrate(bitrate)
	}
	logger.Info("quality tier applied",
		"level", level, "bitrate", bitrate, "session_id", ctx.id)
}

// ---------------------------------------------------------------------------
// SessionCtx goroutine
// ---------------------------------------------------------------------------

// run is the SessionCtx goroutine main loop. It processes events from the
// eventQueue sequentially and handles the WebRTC lifecycle.
func (ctx *SessionCtx) run() {
	defer close(ctx.done)
	defer ctx.cleanup()

	logger.Info("session goroutine started", "session_id", ctx.id)

	for {
		select {
		case <-ctx.stopChan:
			logger.Info("session goroutine stopped via stopChan",
				"session_id", ctx.id)
			return

		case msg, ok := <-ctx.eventQueue:
			if !ok {
				return
			}
			switch msg.Type {
			case common.TypeOffer:
				if err := ctx.handleOffer(msg); err != nil {
					logger.Error("handle offer failed", "err", err,
						"session_id", ctx.id)
					ctx.ws.Send(common.WsMsg{
						Type: common.TypeError, PCID: err.Error(),
						Message:   err.Error(),
						SessionID: ctx.id,
					})
				}

			case common.TypeIceCandidate:
				if msg.Candidate == nil {
					continue
				}
				if ctx.peer == nil {
					// Browser trickles candidates right after the offer, but
					// the peer is only created once the scrcpy session is
					// ready. Buffer instead of silently dropping.
					ctx.pendingCandidates = append(ctx.pendingCandidates, msg.Candidate)
					logger.Info("buffered ICE candidate (peer not ready)",
						"count", len(ctx.pendingCandidates),
						"session_id", ctx.id)
					continue
				}
				if err := ctx.peer.AddICECandidate(
					msg.Candidate.Candidate,
					msg.Candidate.SDPMid,
					msg.Candidate.SDPMLineIndex,
				); err != nil {
					logger.Warn("add ice candidate failed", "err", err,
						"session_id", ctx.id)
				}

			case common.TypeFirstFrame:
				logger.Info("[FRONTEND] first frame rendered",
					"data", msg.Data, "session_id", ctx.id)

			case common.TypeDecoderStats:
				if fd, ok := msg.Data["framesDecoded"]; ok && ctx.peer != nil {
					if decoded, ok2 := toUint32(fd); ok2 {
						ctx.peer.UpdateFramesDecoded(decoded)
					}
				}

			case common.TypeDecoderStatus:
				if ctx.peer != nil {
					lossRate := getFloat64(msg.Data, "lossRate")
					rttMs := getFloat64(msg.Data, "rttMs")
					ctx.peer.UpdateQoS(lossRate, rttMs)
				}
				ctx.maybeAdjustBitrate(msg.Data)

			case common.TypeResetVideo:
				logger.Warn("[FRONTEND] manual/auto keyframe request",
					"session_id", ctx.id)
				ctx.sendCtrl(gateway.BuildResetVideo())

			case "set_quality":
				level, _ := msg.Data["level"].(string)
				ctx.applyQuality(level)

			default:
				logger.Warn("session unknown msg type",
					"type", msg.Type, "session_id", ctx.id)
			}

			// Debug hooks: periodic metric sampling + auto-stop when the
			// collection duration expires. Both are no-ops when debug is
			// nil (open-source builds).
			if ctx.debug != nil {
				ctx.debug.OnSessionEvent(ctx.sessionMetrics())
				if ctx.debug.Active() && ctx.debug.Remaining() == 0 {
					ctx.debug.HandleControl("debug_stop", nil)
				}
			}
		}
	}
}

// sessionMetrics collects a snapshot of internal session state for the
// debug hooks. Plain counter reads; harmless in open-source builds.
func (ctx *SessionCtx) sessionMetrics() debughooks.SessionMetrics {
	m := debughooks.SessionMetrics{
		EventQLen: len(ctx.eventQueue),
		Bitrate:   ctx.lastBitrate,
	}
	var sessState string
	var paused bool
	ctx.mu.Lock()
	s := ctx.session
	ctx.mu.Unlock()
	if s != nil {
		m.VideoChLen = len(s.VideoCh)
		m.CtrlChLen = len(s.CtrlCh)
		sessState = string(s.State())
		paused = s.ForwardPaused()
	}
	m.SessionState = sessState
	m.Paused = paused
	if ctx.peer != nil {
		m.PeerState = ctx.peer.PeerState()
	}
	return m
}

// ---------------------------------------------------------------------------
// SessionCtx: handleOffer (moved from Controller)
// ---------------------------------------------------------------------------

func (ctx *SessionCtx) handleOffer(msg common.WsMsg) error {
	if msg.Offer == nil {
		return fmt.Errorf("missing offer")
	}

	// Release any old peer so we start fresh.
	ctx.releasePeer()

	// Record initial bitrate so the QoS ladder scales proportionally.
	if ctx.initialBitrate == 0 {
		ctx.initialBitrate = ctx.ctrl.Config().Scrcpy.VideoBitRate
		ctx.lastBitrate = ctx.initialBitrate
	}

	serial := ctx.inst.DeviceSerial
	cfg := ctx.ctrl.Config()
	scfg := cfg.Scrcpy

	// Use ICE servers from this session's snapshot
	stun := ctx.signalingSTUN
	turn := ctx.signalingTURN
	if len(stun) == 0 {
		stun = cfg.STUNServers
	}
	if turn == nil {
		turn = cfg.TURNServer
	}

	// Create the peer IMMEDIATELY — do NOT wait for the scrcpy session.
	// ICE gathering and connectivity checks then run concurrently with the
	// (multi-second) device startup. The answer uses the configured codec
	// and the default profile-level-id; the device-probed value is logged
	// later by prepareSession (negotiation observed working with 42e01f).
	logger.Info("creating peer manager",
		"serial", serial,
		"stun_count", len(stun),
		"turn", turn != nil,
		"session_id", ctx.id)

	pm, err := bridgewebrtc.NewPeerManager(
		serial, stun, turn,
		scfg.VideoCodec, "42e01f",
		scfg.AudioCodec,
		scfg.AudioEnabled,
		ctx.debug,
	)
	if err != nil {
		return fmt.Errorf("create peer manager: %w", err)
	}
	ctx.peer = pm
	// Hand the hooks a way to push debug logs over the browser DataChannel.
	if ctx.debug != nil {
		ctx.debug.BindPeer(pm.SendControl)
	}

	ctx.mu.Lock()
	ctx.sessionReady = make(chan struct{})
	ctx.mu.Unlock()

	// Sync the encoder bitrate into the FEC evaluator
	pm.SetCurrentBitrate(ctx.initialBitrate)
	pm.SetFECAutoDisabled(scfg.FECDisabled)

	// Wire up control callbacks
	pm.SetOnControlRecv(func(data []byte) {
		var ctrl map[string]any
		if err := json.Unmarshal(data, &ctrl); err != nil {
			return
		}
		msgType, _ := ctrl["type"].(string)
		ctx.dispatchControl(msgType, ctrl)
	})

	// PLI L1/L2 → lightweight IDR request (0x17), no encoder reset.
	pm.SetOnRequestKeyframe(func() {
		ctx.sendCtrl(gateway.BuildRequestKeyframe())
	})

	// PLI L3 / FIR → full encoder reset (0x11), last resort.
	pm.SetOnResetVideo(func() {
		ctx.sendCtrl(gateway.BuildResetVideo())
	})

	// Trickle ICE: register the candidate relay BEFORE HandleOffer.
	// ICE gathering starts inside HandleOffer at SetLocalDescription, so the
	// callback must already be in place — otherwise every gathered candidate
	// is lost and the answer stays the browser's only source of candidates.
	pm.SetOnICECandidate(func(candidate string, sdpMid *string, sdpMLineIndex *uint16) {
		ctx.ws.Send(common.WsMsg{
			Type: common.TypeIceCandidate,
			Candidate: &common.IceCandidate{
				Candidate:     candidate,
				SDPMid:        sdpMid,
				SDPMLineIndex: sdpMLineIndex,
			},
			SessionID: ctx.id,
		})
	})

	answer, err := pm.HandleOffer(msg.Offer.SDP, msg.Offer.Type)
	if err != nil {
		logger.Error("SDP negotiation failed", "err", err, "session_id", ctx.id)
		return fmt.Errorf("SDP negotiation failed: %w", err)
	}

	// Flush candidates that were trickled by the browser before the peer
	// existed. Safe now: HandleOffer has set the remote description.
	if len(ctx.pendingCandidates) > 0 {
		logger.Info("flushing buffered ICE candidates",
			"count", len(ctx.pendingCandidates),
			"session_id", ctx.id)
		for _, c := range ctx.pendingCandidates {
			if err := pm.AddICECandidate(c.Candidate, c.SDPMid, c.SDPMLineIndex); err != nil {
				logger.Warn("flush buffered ice candidate failed", "err", err,
					"session_id", ctx.id)
			}
		}
		ctx.pendingCandidates = nil
	}

	// Peer connected → wait for the scrcpy session (still starting up in the
	// background), then unpause and start media.
	pm.SetOnConnected(func() {
		ctx.deviceState.Store(deviceBusy)
		ctx.ctrl.reportDeviceStatus()
		logger.Info("peer connected, waiting for scrcpy session",
			"serial", serial, "session_id", ctx.id)
		go func() {
			ctx.mu.Lock()
			ready := ctx.sessionReady
			ctx.mu.Unlock()
			select {
			case <-ready:
			case <-ctx.stopChan:
				return
			}
			session := ctx.getSession()
			if session == nil {
				logger.Warn("peer connected but session unavailable",
					"serial", serial, "session_id", ctx.id)
				return
			}
			logger.Info("scrcpy session ready, starting media pumps",
				"serial", serial, "session_id", ctx.id)
			session.SendControl(gateway.BuildStartAudio())
			// Re-sync the encoder with the selected quality tier — a warm
			// (reused) session may still run a previous session's bitrate,
			// and a fresh session always starts at video_bit_rate.
			if ctx.lastBitrate > 0 {
				session.SendControl(gateway.BuildChangeBitrate(ctx.lastBitrate))
			}
			// Request an IDR so the browser can start decoding immediately
			// instead of waiting for the next periodic keyframe (crucial for
			// warm reuse, where the stream does not restart on its own).
			session.SendControl(gateway.BuildRequestKeyframe())
			session.SetForwardPaused(false)
			pm.StartMediaPumps(session.VideoCh, session.AudioCh, session.CtrlCh)
		}()
	})

	// Send answer back through signaling (immediately — ICE checks start now,
	// overlapping the scrcpy server startup below)
	ctx.ws.Send(common.WsMsg{
		Type: common.TypeAnswer,
		Answer: &common.SessionDesc{
			SDP:  answer.SDP,
			Type: answer.Type.String(),
		},
		SessionID: ctx.id,
	})

	// Start the scrcpy session in the background. This takes several seconds
	// (adb push, server spawn, encoder init) and previously blocked the whole
	// offer path; it now runs concurrently with ICE. Duplicate offers are
	// guarded by prepareOnce so only the first offer starts a prepare.
	ctx.prepareOnce.Do(func() { go ctx.prepareSession() })

	return nil
}

// prepareSession acquires (or reuses) the scrcpy session and signals
// readiness via sessionReady. Runs in its own goroutine.
func (ctx *SessionCtx) prepareSession() {
	serial := ctx.inst.DeviceSerial

	session, reused, err := ctx.mgr.Acquire(serial)
	if err != nil {
		logger.Error("prepare session failed", "err", err, "session_id", ctx.id)
		ctx.ws.Send(common.WsMsg{
			Type:      common.TypeError,
			PCID:      fmt.Sprintf("acquire session: %v", err),
			Message:   fmt.Sprintf("acquire session: %v", err),
			SessionID: ctx.id,
		})
		return
	}
	if reused {
		logger.Info("scrcpy session reused from warm pool, skipping cold start",
			"serial", serial, "session_id", ctx.id)
	}

	ctx.mu.Lock()
	// The session context may have been stopped while Acquire was blocking.
	select {
	case <-ctx.stopChan:
		ctx.mu.Unlock()
		ctx.mgr.Release(serial)
		session.Release()
		return
	default:
	}
	ctx.session = session
	ready := ctx.sessionReady
	ctx.mu.Unlock()

	// Watch for scrcpy server death mid-session. Without this the browser
	// just sees a frozen frame forever (Died() had no consumer).
	go ctx.watchSessionDeath(session)

	// Start forwarders in paused mode; frames buffer until ICE connects and
	// the media pumps unpause forwarding.
	session.StartForwarders()
	session.SetForwardPaused(true)

	// Probe profile-level-id for observability only — the answer already
	// went out with the configured default.
	plid := session.WaitProfileLevelID(2 * time.Second)
	logger.Info("profile-level-id ready (post-answer)", "serial", serial,
		"plid", plid, "session_id", ctx.id)

	// Don't close sessionReady if the session context was torn down while we
	// were waiting (cleanup may have already released everything). safeClose
	// additionally guards against any concurrent close path.
	select {
	case <-ctx.stopChan:
		return
	default:
	}
	ctx.safeCloseReady(ready)
	logger.Info("scrcpy session ready", "serial", serial, "session_id", ctx.id)
}

// safeCloseReady closes the sessionReady channel, tolerating a concurrent
// close (defense in depth on top of prepareOnce).
func (ctx *SessionCtx) safeCloseReady(ready chan struct{}) {
	defer func() {
		if r := recover(); r != nil {
			logger.Warn("sessionReady close raced, ignored",
				"session_id", ctx.id, "panic", r)
		}
	}()
	close(ready)
}

// getSession returns the current scrcpy session (nil while still starting).
func (ctx *SessionCtx) getSession() *gateway.Session {
	ctx.mu.Lock()
	defer ctx.mu.Unlock()
	return ctx.session
}

// watchSessionDeath notifies the browser when the scrcpy server process
// dies mid-session. The frontend treats stream_dead like a connection loss
// and auto-reconnects; Acquire then cold-starts a fresh server (the warm
// pool's Alive() check rejects the dead session).
func (ctx *SessionCtx) watchSessionDeath(s *gateway.Session) {
	select {
	case <-s.Died():
		// Normal cleanup also closes Died (forwarders exit on Release);
		// only report if this context is still alive.
		select {
		case <-ctx.stopChan:
			return
		default:
		}
		logger.Error("scrcpy server died mid-session, notifying browser",
			"serial", ctx.inst.DeviceSerial, "session_id", ctx.id)
		ctx.ws.Send(common.WsMsg{Type: common.TypeStreamDead, SessionID: ctx.id})
		if ctx.ctrl.hooks != nil {
			ctx.ctrl.hooks.OnStreamDead(ctx.inst.DeviceSerial, ctx.inst.InstanceID, ctx.id)
		}
	case <-ctx.stopChan:
	}
}

// sendCtrl delivers a scrcpy control message if the session is up.
func (ctx *SessionCtx) sendCtrl(b []byte) {
	if s := ctx.getSession(); s != nil {
		_ = s.SendControl(b)
		if ctx.debug != nil {
			ctx.debug.OnControlSent(b)
		}
	}
}

// dispatchControl handles a decoded control message {type, data map[string]any}
// for the session: builds the scrcpy control bytes and sends them. 共享自
// 浏览器 DataChannel 路径（SetOnControlRecv）与平台 gRPC SendControl 路径。
func (ctx *SessionCtx) dispatchControl(msgType string, ctrl map[string]any) {
	switch msgType {
	case "inject_touch":
		d, _ := ctrl["data"].(map[string]any)
		pointerID := getUint64PointerID(d, "pointer_id")
		b := gateway.BuildInjectTouch(
			byte(getFloat64(d, "action")),
			pointerID,
			uint32(getFloat64(d, "x")),
			uint32(getFloat64(d, "y")),
			uint16(getFloat64(d, "width")),
			uint16(getFloat64(d, "height")),
			getFloat64(d, "pressure"),
			uint32(getFloat64(d, "action_button")),
			uint32(getFloat64(d, "buttons")),
		)
		// Debug hooks: record DC → scrcpy injection latency when the
		// frontend stamped the touch with a timestamp (closed-source).
		if ctx.debug != nil && ctx.debug.Active() {
			if ts, ok := d["ts"].(float64); ok {
				ctx.debug.Logf("[touch] action=%d dc->scrcpy latency=%.1fms",
					byte(getFloat64(d, "action")),
					float64(time.Now().UnixMilli())-ts)
			}
		}
		ctx.sendCtrl(b)
	case "inject_scroll":
		d, _ := ctrl["data"].(map[string]any)
		b := gateway.BuildInjectScroll(
			uint32(getFloat64(d, "x")), uint32(getFloat64(d, "y")),
			uint16(getFloat64(d, "width")), uint16(getFloat64(d, "height")),
			getFloat64(d, "hscroll"), getFloat64(d, "vscroll"),
			uint32(getFloat64(d, "buttons")),
		)
		ctx.sendCtrl(b)
	case "inject_keycode":
		d, _ := ctrl["data"].(map[string]any)
		b := gateway.BuildInjectKeycode(
			uint32(getFloat64(d, "action")),
			uint32(getFloat64(d, "keycode")),
			uint32(getFloat64(d, "repeat")),
			uint32(getFloat64(d, "metastate")),
		)
		ctx.sendCtrl(b)
	case "inject_text":
		d, _ := ctrl["data"].(map[string]any)
		text, _ := d["text"].(string)
		ctx.sendCtrl(gateway.BuildInjectText(text))
	case "back_or_screen_on":
		d, _ := ctrl["data"].(map[string]any)
		ctx.sendCtrl(gateway.BuildBackOrScreenOn(byte(getFloat64(d, "action"))))
	case "set_clipboard":
		d, _ := ctrl["data"].(map[string]any)
		seq := uint64(getFloat64(d, "sequence"))
		paste := getFloat64(d, "paste") != 0
		text, _ := d["text"].(string)
		ctx.sendCtrl(gateway.BuildSetClipboard(seq, paste, text))
	case "set_display_power":
		d, _ := ctrl["data"].(map[string]any)
		on := getFloat64(d, "on") != 0
		ctx.sendCtrl(gateway.BuildSetDisplayPower(on))
	case "rotate_device":
		ctx.sendCtrl(gateway.BuildRotateDevice())
	case "collapse_panels":
		ctx.sendCtrl(gateway.BuildCollapsePanels())
	case "expand_notification", "inject_notification":
		ctx.sendCtrl(gateway.BuildExpandNotificationPanel())
	case "expand_settings":
		ctx.sendCtrl(gateway.BuildExpandSettingsPanel())
	case "get_clipboard":
		d, _ := ctrl["data"].(map[string]any)
		copyKey := byte(getFloat64(d, "copy_key"))
		ctx.sendCtrl(gateway.BuildGetClipboard(copyKey))
	case "open_hard_keyboard_settings":
		ctx.sendCtrl(gateway.BuildOpenHardKeyboardSettings())
	case "reset_video":
		ctx.sendCtrl(gateway.BuildResetVideo())
	case "set_quality":
		// 用户切换清晰度档位（清晰/高清/原画）——只改编码器码率，
		// 分辨率固定不变。经 eventQueue 串行应用，避免与
		// maybeAdjustBitrate 的读写竞争。
		d, _ := ctrl["data"].(map[string]any)
		level, _ := d["level"].(string)
		select {
		case ctx.eventQueue <- common.WsMsg{Type: "set_quality", Data: map[string]any{"level": level}}:
		default:
			logger.Warn("set_quality dropped: event queue full", "session_id", ctx.id)
		}
	default:
		// Unknown control types are offered to the debug hooks first
		// (debug_start/debug_stop/debug_fetch etc. in closed-source
		// builds). In open-source builds ctx.debug is nil and every
		// unknown message falls through to the warning.
		if ctx.debug != nil && ctx.debug.HandleControl(msgType, ctrl) {
			return
		}
		logger.Warn("unknown control type", "type", msgType)
	}
}

// ---------------------------------------------------------------------------
// SessionCtx: cleanup (scrcpy session goes to the warm pool, not killed)
// ---------------------------------------------------------------------------

// cleanup releases all resources held by this SessionCtx. The scrcpy session
// itself is NOT released here — it goes back to the Manager's warm pool
// (ReleaseDeferred) and stays alive for scrcpy.warm_keep_seconds so a
// reconnect skips the multi-second cold start. The Manager owns the session
// lifecycle from this point (expireWarm releases it when the window lapses).
func (ctx *SessionCtx) cleanup() {
	logger.Info("session cleanup started", "session_id", ctx.id)

	// 1. Close peer (stops media pumps, closes PeerConnection)
	if ctx.peer != nil {
		_ = ctx.peer.Close()
		ctx.peer = nil
	}

	// 2. Hand the scrcpy session to the warm pool. Forwarding is paused by
	//    ReleaseDeferred; if the session already died it is released
	//    immediately instead.
	ctx.mu.Lock()
	session := ctx.session
	ctx.session = nil
	ctx.mu.Unlock()

	if session != nil {
		warmKeep := time.Duration(ctx.ctrl.Config().Scrcpy.WarmKeepSeconds) * time.Second
		if warmKeep <= 0 {
			warmKeep = 5 * time.Minute
		}
		ctx.mgr.ReleaseDeferred(ctx.inst.DeviceSerial, warmKeep)
	}

	// Drain event queue so senders don't block
	for {
		select {
		case <-ctx.eventQueue:
		default:
			goto drained
		}
	}
drained:

	logger.Info("session cleanup complete", "session_id", ctx.id)
}

// releasePeer closes the PeerManager if one is active.
func (ctx *SessionCtx) releasePeer() {
	if ctx.peer != nil {
		_ = ctx.peer.Close()
		ctx.peer = nil
	}
}

// ---------------------------------------------------------------------------
// Bitrate hysteresis (per-session, moved from Controller)
// ---------------------------------------------------------------------------

const (
	bitrateHysteresis    = 30 * time.Second
	bitrateRecoveryStale = 30 * time.Second
	// If a single drop exceeds this fraction, log a warning — the BWE is
	// reacting too aggressively and may overshoot into a death spiral.
	aggressiveDropThreshold = 0.50 // 50 %
)

// bitrateStep computes a target bitrate as a fraction of the initial
// bitrate read from config. It is clamped to minBitrate so the encoder
// never enters a zombie stream (30 kbps is unusable for cloud gaming).
func (ctx *SessionCtx) bitrateStep(lossRate float64) int {
	if ctx.initialBitrate == 0 {
		return 8_000_000 // fallback
	}
	var target int
	switch {
	case lossRate > 10.0:
		target = ctx.initialBitrate / 4 // 25 %
	case lossRate > 5.0:
		target = ctx.initialBitrate / 2 // 50 %
	case lossRate > 2.0:
		target = ctx.initialBitrate * 3 / 4 // 75 %
	default:
		target = ctx.initialBitrate // 100 % (recovery target)
	}
	if target < ctx.minBitrate {
		target = ctx.minBitrate
	}
	return target
}

// maybeAdjustBitrate evaluates loss rate and triggers a bitrate downgrade
// on the Android encoder when the network appears congested.
func (ctx *SessionCtx) maybeAdjustBitrate(data map[string]any) {
	if ctx.getSession() == nil {
		return
	}

	lossRate := getFloat64(data, "lossRate")

	// QoS 采样上报（节流在 host hooks 实现侧按 qos_interval_ms 处理）。
	if ctx.ctrl.hooks != nil {
		ctx.ctrl.hooks.OnQoS(QoSReport{
			SessionID:  ctx.id,
			Serial:     ctx.inst.DeviceSerial,
			InstanceID: ctx.inst.InstanceID,
			LossRate:   lossRate,
			RTTMs:      getFloat64(data, "rttMs"),
			Bitrate:    ctx.lastBitrate,
		})
	}

	// Track how long the network has been quiet — used for recovery.
	if lossRate < 2.0 {
		if ctx.lastLossLowTime.IsZero() {
			ctx.lastLossLowTime = time.Now()
		}
	} else {
		ctx.lastLossLowTime = time.Time{} // reset on any spike
	}

	prev := ctx.lastBitrate
	target := ctx.bitrateStep(lossRate)

	if target == prev {
		return
	}

	// Downgrade is allowed immediately (with hysteresis).
	if target < prev {
		if time.Since(ctx.lastBitrateChange) < bitrateHysteresis {
			return
		}
		// Check for overly aggressive BWE drop.
		dropPct := float64(prev-target) / float64(prev)
		ctx.lastBitrateDropPct = dropPct
		if dropPct > aggressiveDropThreshold {
			logger.Warn("aggressive bitrate drop detected",
				"session_id", ctx.id,
				"drop_pct", fmt.Sprintf("%.0f%%", dropPct*100),
				"prev", prev,
				"target", target,
				"lossRate", fmt.Sprintf("%.1f%%", lossRate))
		}
	}

	// Upgrade (recovery): require sustained low loss for 30 s.
	if target > prev {
		if prev == 0 {
			// First adjustment: set initial bitrate immediately
		} else if ctx.lastLossLowTime.IsZero() || time.Since(ctx.lastLossLowTime) < bitrateRecoveryStale {
			return
		}
	}

	ctx.lastBitrate = target
	ctx.lastBitrateChange = time.Now()
	ctx.lastLossLowTime = time.Time{} // reset recovery timer
	ctx.sendCtrl(gateway.BuildChangeBitrate(target))
	if ctx.debug != nil {
		ctx.debug.Logf("[bwe] bitrate %d -> %d (loss=%.1f%%)",
			prev, target, lossRate)
	}

	// Keep the FEC evaluator in sync with the current encoder bitrate
	if ctx.peer != nil {
		ctx.peer.SetCurrentBitrate(target)
	}

	logger.Info("bitrate adjusted",
		"serial", ctx.inst.DeviceSerial,
		"lossRate", fmt.Sprintf("%.1f%%", lossRate),
		"bitrate", target/1_000_000,
		"prev", prev/1_000_000,
		"minBitrate", ctx.minBitrate/1_000_000,
		"session_id", ctx.id)
}

// ---------------------------------------------------------------------------
// Controller: shutdown all sessions
// ---------------------------------------------------------------------------

// shutdownAll stops all active SessionCtx goroutines.
func (c *Controller) shutdownAll() {
	c.mu.Lock()
	var ids []string
	for id, ctx := range c.sessions {
		ids = append(ids, id)
		logger.Info("shutting down session", "session_id", id)
		select {
		case <-ctx.stopChan:
		default:
			close(ctx.stopChan)
		}
	}

	// Clear all state
	c.sessions = make(map[string]*SessionCtx)
	c.currentSessionID = ""
	c.deviceState.Store(deviceIdle)
	c.mu.Unlock()

	// 事件上报放锁外（hooks 实现可能回调，避免持 c.mu 递归）。
	if c.hooks != nil {
		for _, id := range ids {
			c.hooks.OnSessionStopped(c.inst.DeviceSerial, c.inst.InstanceID, id, "agent_stop")
		}
		c.reportDeviceStatus()
	}
}

// ---------------------------------------------------------------------------
// Helper functions (package-level, shared)
// ---------------------------------------------------------------------------

func getUint64PointerID(m map[string]any, key string) uint64 {
	if m == nil {
		return gateway.PointerIDGenericFinger
	}
	v, ok := m[key]
	if !ok {
		return gateway.PointerIDGenericFinger
	}
	switch val := v.(type) {
	case float64:
		return uint64(int64(val))
	case int64:
		return uint64(val)
	case int:
		return uint64(val)
	default:
		return gateway.PointerIDGenericFinger
	}
}

func getFloat64(m map[string]any, key string) float64 {
	if m == nil {
		return 0
	}
	v, ok := m[key]
	if !ok {
		return 0
	}
	switch val := v.(type) {
	case float64:
		return val
	case int:
		return float64(val)
	case bool:
		if val {
			return 1
		}
		return 0
	default:
		return 0
	}
}

func toUint32(v any) (uint32, bool) {
	switch val := v.(type) {
	case float64:
		return uint32(val), true
	case uint32:
		return val, true
	case int:
		return uint32(val), true
	default:
		return 0, false
	}
}
